# Generated by Django 4.2 on 2023-07-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0013_alter_repositories_is_project_created'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='github.repositories'),
        ),
    ]
