# Generated by Django 4.2 on 2023-07-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='repository_url',
        ),
    ]
