# Generated by Django 4.2 on 2023-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=200, null=True)),
                ('line', models.IntegerField(null=True)),
                ('exception', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
