# Generated by Django 4.2 on 2023-07-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logerror',
            name='exception',
        ),
        migrations.AddField(
            model_name='logerror',
            name='mensage',
            field=models.TextField(null=True),
        ),
    ]
