# Generated by Django 4.2 on 2023-07-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_logerror_exception_logerror_mensage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logerror',
            old_name='function',
            new_name='nm_function',
        ),
        migrations.AddField(
            model_name='logerror',
            name='nm_class',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='logerror',
            name='nm_file',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
