# Generated by Django 4.2 on 2023-07-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_function_logerror_nm_function_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logerror',
            old_name='mensage',
            new_name='message',
        ),
    ]
