# Generated by Django 4.2 on 2023-06-11 00:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_hobbies_professionalinfos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('who_am_i', models.TextField(null=True)),
                ('career_summary', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
            managers=[
                ('normal_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='Hobbies',
        ),
        migrations.DeleteModel(
            name='PersonalInfos',
        ),
        migrations.DeleteModel(
            name='ProfessionalInfos',
        ),
        migrations.DeleteModel(
            name='Stacks',
        ),
    ]
