# Generated by Django 4.2 on 2023-06-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0004_infos_delete_hobbies_delete_personalinfos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infos',
            old_name='career_summary',
            new_name='career',
        ),
    ]
