# Generated by Django 4.2 on 2023-07-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0006_contactinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
