# Generated by Django 4.2 on 2023-09-05 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
