# Generated by Django 4.2 on 2023-04-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commits',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='github.repositories'),
        ),
    ]
