# Generated by Django 4.2 on 2023-04-20 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_commits_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commits',
            name='parents_sha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='github.commits'),
        ),
    ]
