# Generated by Django 4.2 on 2023-04-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_alter_commits_parents_sha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commits',
            old_name='parents_sha',
            new_name='parents',
        ),
        migrations.RemoveField(
            model_name='commits',
            name='id',
        ),
        migrations.AlterField(
            model_name='commits',
            name='sha',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
