# Generated by Django 4.2 on 2023-04-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_rename_parents_sha_commits_parents_remove_commits_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commits',
            name='parents',
        ),
    ]
