# Generated by Django 4.2 on 2023-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_remove_commits_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositories',
            name='is_finished',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='repositories',
            name='is_professional',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='repositories',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
