# Generated by Django 4.2 on 2023-04-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_repositories_is_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositories',
            name='is_aproved',
            field=models.BooleanField(default=False),
        ),
    ]
