# Generated by Django 4.2 on 2023-04-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0007_repositories_is_aproved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositories',
            old_name='is_aproved',
            new_name='is_approved',
        ),
    ]
