# Generated by Django 4.2 on 2023-04-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0008_rename_is_aproved_repositories_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositories',
            name='is_published',
            field=models.BooleanField(null=True),
        ),
    ]
