# Generated by Django 4.2 on 2023-06-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0009_repositories_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositories',
            name='project_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='repositories',
            name='repository_url',
            field=models.URLField(null=True),
        ),
    ]
