# Generated by Django 4.2 on 2023-07-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0010_repositories_project_url_repositories_repository_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositories',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
