# Generated by Django 4.2 on 2023-07-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0011_repositories_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositories',
            name='description',
        ),
        migrations.RemoveField(
            model_name='repositories',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='repositories',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='repositories',
            name='is_professional',
        ),
        migrations.RemoveField(
            model_name='repositories',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='repositories',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='repositories',
            name='repository_url',
        ),
        migrations.RemoveField(
            model_name='repositories',
            name='title',
        ),
        migrations.AddField(
            model_name='repositories',
            name='is_project_created',
            field=models.BooleanField(null=True),
        ),
    ]
