# Generated by Django 4.2 on 2023-07-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0012_remove_repositories_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='is_project_created',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
